name: aitaku
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  table_calendar: ^3.1.2
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  font_awesome_flutter: ^10.1.0
  amplify_flutter: ^2.4.1
  amplify_auth_cognito: ^2.4.1
  amplify_authenticator: ^2.1.3
  flutter_secure_storage: ^7.0.0

dependency_overrides:
  win32: null
  win32_registry: null

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/250x250.png
    - assets/images/welcome_screen.png