name: aitaku
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  table_calendar: ^3.0.0

  cupertino_icons: ^1.0.8
  http: ^1.1.0  # Use the latest version available

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/250x250.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/250x250.png"
